# Generated by Django 5.1 on 2024-08-31 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpage',
            name='media_type',
            field=models.CharField(choices=[('d', 'image'), ('v', 'video')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
