# Generated by Django 5.1 on 2024-09-01 18:56

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adpage_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpage',
            name='img',
        ),
        migrations.AddField(
            model_name='adpage',
            name='media',
            field=models.FileField(default='none', upload_to=home.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adpage',
            name='user',
            field=models.ForeignKey(default='ananymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adpage',
            name='media_type',
            field=models.CharField(choices=[('i', 'image'), ('v', 'video')], max_length=1),
        ),
    ]
