# Generated by Django 5.1 on 2024-09-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_adpage_img_adpage_media_adpage_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adpage',
            old_name='media',
            new_name='img',
        ),
    ]
